language: php
php:
  - 5.5

before_script:
  # webserver setup
  - composer install
  - sudo sed -i -e "/DocumentRoot/i\ServerName flot1.dev" /etc/apache2/sites-available/default
  - echo "127.0.0.1 flot1.dev" | sudo tee -a /etc/hosts
  - sudo /etc/init.d/apache2 restart
  - sleep 3
